### ISSUE TITLE
KeyError: 14

### ISSUE THREAD

**Issue by Norina28** [HubertTang/PLASMe#14]
Hello,
I was trying to use the tool but I got this error:
`Align the contigs to the reference plasmids ... ...`
`19 contigs are aligned to the reference database.`
`Predict the proteins in contigs ... ...`
`Align the proteins to PC database ... ...`
`Predict using PLASMe ... ...`
`Traceback (most recent call last):`
`  File "/home/PLASMe/PLASMe.py", line 591, in <module>`
`    plasme_output(rst_path=f"{temp_dir}/PLASMe_candidate.csv", `
`  File "/home/PLASMe/PLASMe.py", line 495, in plasme_output
    out_info.write(f"{contig}\t{len(contig_seq_index[contig].seq)}\t{query_ref_dict[contig]}\t{order}\t{evidence}\t{score}\t{','.join(out_m)}\n")
  File "/home/mambaforge/envs/plasme/lib/python3.9/site-packages/Bio/File.py", line 238, in __getitem__
    record = self._proxy.get(self._offsets[key])`
`KeyError: 14
`

Does anyone know what is the issue?

Thank you!

Ele

**Comment by Norina28** [comment]
I thought I had solved but I have not.

Any idea?
